name: updater

on:
  schedule:
    - cron: '0 5 * * Mon/7'
      # Runs every week to get latest packages

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.0.4'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project src/update.jl 
